### ISSUE TITLE
Collect coverage information from unit and integration tests

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#104]

**Comment by kyessenov** [comment]
If anyone is interested in extracting coverage from k8s pods, feel free to tackle this!
We're at a pretty low coverage right now, and we need to improve the situation.

**Comment by ayj** [comment]
AFAICT, golang test coverage is only gathered from go unit tests, i.e. "go test -cover". There doesn't seem to be a way to extract coverage stats from non-tests. If we wanted to improve test coverage we'd need to (a) beef up existing tests (e.g. with k8s/envoy mocks) and/or write additional  unit tests that run on pods that can verify the glue logic that isn't covered by mocks, etc.

**Comment by ayj** [comment]
Starting to work on this. First step is getting basic unit test coverage published to github.com/istio/manager via jenkins. We can then follow-up with incremental PR to increase coverage.

**Comment by kyessenov** [comment]
Thanks! Take a look at mixer set-up with code coverage website integration. The problem with bazel tests is that it's really hard to do e2e stuff like iptables and envoy call-out. So we might need to do extensive mocking to get unit tests working for config generation.

**Comment by ayj** [comment]
Codecov integration is in with https://github.com/istio/manager/pull/171 and 
https://github.com/istio/manager/pull/174. 

I'll start looking at increasing the code coverage % next week.
