### ISSUE TITLE
Uniqueness of destination policies

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#125]
We define a `Destination` policy schema that provides routing policies for a service version destination, e.g. use "round_robin" for service "a" versions "v1". Currently, you can define multiple such policies for the same service version, with unspecified semantics of what happens then. The right solution would be to enforce uniqueness per service version. This can be accomplished in etcd by using service name and version as part of the resource name. Should we use the service key (a:version=v1) as the name of the policy?

**Comment by rshriram** [comment]
fixed

**Comment by kyessenov** [comment]
It's not fixed, please reopen. Feel free to move to beta.
