### ISSUE TITLE
Generate envoy virtual host entry for pod IP and port

### ISSUE THREAD

**Issue by rshriram** [istio/manager#150]
Ingress controllers like Nginx use the pod IP instead of service IP. In such a case, Envoy drops the incoming request as the host headers no longer match. Currently the proxy config generator creates virtual hosts only for all variations of service name and the service cluster IP. It needs to take the local pod IP into account as well.
cc @kyessenov

**Comment by kyessenov** [comment]
Is it important to support pod IPs directly? There's a lot more churn in the pod registry, to the point we add this now, Envoy will be constantly restarting.

**Comment by kyessenov** [comment]
Or is this just for inbound connection?

**Comment by rshriram** [comment]
Its inbound.. from an ingress controller. Just to be able to match the pod's local IP, when its present in the host field.
I don't think we need to restart at all.

**Comment by zcahana** [comment]
I'm hitting this as well when testing the envoy-based ingress controller in #71.

I'm assigning this to myself as I plan to work on it on Sunday (yes it's a working day in here...).
If anyone else wanna give it a go before, that's fine too.

**Comment by zcahana** [comment]
Oh, I didn't notice this is already assigned to @kyessenov. So, if you don't get the time to work it and want me to roll it next week, let me know.
