### ISSUE TITLE
Consider auto-generating golang structs for envoy configuration from JSON schema

### ISSUE THREAD

**Issue by ayj** [istio/manager#185]
Hand generating and maintaining envoy configuration structs (i.e. proxy/envoy/resources.go) is a bit cumbersome. We could possibly auto-generate golang-based structs with JSON annotations from envoy's [JSON schema definitions](https://github.com/lyft/envoy/blob/master/source/common/json/config_schemas.cc) using one of the tools list [here](https://adrianhesketh.com/2016/07/19/json-schema-to-go-struct-generator-roundup/). Envoy's configuration is defined as multiple separate JSON schema so we'd still end up writing some additional generation code even with an existing JSON-schema-to-golang library. This approach may end up being more trouble than it's worth, but it might be worth considering.

**Comment by rshriram** [comment]
We could always collate all the config into one big JSON schema and generate go struct

**Comment by kyessenov** [comment]
Sounds like a good idea. When we started, we didn't have swagger schema. We'll loose the extra fields in the structs that are convenient for AST manipulation though.

**Comment by ayj** [comment]
Switching to [Envoy v2 API](https://github.com/lyft/envoy-api) will address this issue.
