### ISSUE TITLE
Bazel Mac build is broken

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#20]
Due to ongoing work with fixing rules_go, bazel does not work on Mac.

**Comment by kyessenov** [comment]
...waiting for a resolution on https://github.com/bazelbuild/rules_go/issues/234

**Comment by GregHanson** [comment]
Workaround until bazel defect is resolved:

- Started minikube on Mac
- Started a Linux VM using VirtualBox.
- Copied the `~/.kube/config` and the certs from `~/.minikube` referenced in `config` to my Linux VM inside istio/manager/platform/kube
- modified `config` with the correct filepaths to cert files

**Comment by kyessenov** [comment]
Fixed by #93

**Comment by kyessenov** [comment]
(let's keep this open until we also get cross-compilation; then we can have full docker build on a mac)

**Comment by rshriram** [comment]
Close? Manager builds on MAC
