### ISSUE TITLE
unknown field "precedence" in config.RouteRule

### ISSUE THREAD

**Issue by esnible** [istio/manager#202]
The commands `./manager/bazel-bin/cmd/manager/manager config list route-rule` produces the error ```Error listing route-rule: 1 error occurred:

* unknown field "precedence" in config.RouteRule```

To reproduce,
```
kubectl create -f istio/demos/apps/bookinfo/route-rule-reviews-v1.yaml 
./manager/bazel-bin/cmd/manager/manager config list route-rule
```

**Comment by rshriram** [comment]
is this error still present? @esnible ?
