### ISSUE TITLE
Ingress controller: update ingress resource status

### ISSUE THREAD

**Issue by zcahana** [istio/manager#214]
Ingress resources have a status field, which indicates the external IP addresses/hostname for which the ingress is mapped to. This is normally updated by the ingress controller itself, and is set to the IP address(es) of the node(s) in which the ingress controller(s) run, or the external IP of a LoadBalancer-type service which exposes the ingress controller.

This can be implemented using the [`github.com/kubernetes/ingress/core/pkg/ingress/status`](https://github.com/kubernetes/ingress/tree/master/core/pkg/ingress/status) package, which already does something similar.

**Comment by zcahana** [comment]
Once this issue is resolved, we should change the bookinfo demo so that the the application is accessed via the IP address assigned to the ingress resource (as returned by `kubectl get ingress <ingress_name>`), and not via the LoadBalancer IP and/or hostIP:NodePort of the ingress controller service.

**Comment by kyessenov** [comment]
It's not fully done since the syncer sets the wrong IP.

**Comment by kyessenov** [comment]
Tested with GKE, the ingress status IP is a list of node IPs (3 out of my 5 nodes). Trying to access a node IP on port 80 does not work.

**Comment by ijsnellf** [comment]
This can be closed, right? The syncer either updates the IPs to the node IPs or the associated service IP.
