### ISSUE TITLE
Ingress controller: evaluate kubernetes GenericController as a base implementation

### ISSUE THREAD

**Issue by zcahana** [istio/manager#219]
The [github.com/kubernetes/ingress](https://github.com/kubernetes/ingress/) repo provides a [`GenericController`](https://github.com/kubernetes/ingress/) implementation that aims to be used as a basis for developing ingress controller.

This task is to evaluate whether it makes sense to build our ingress controller on top of that .

**Comment by aledbf** [comment]
@zcahana how can I help? 
I am searching for an alternative to nginx as reverse proxy and istio/envoy looks promising.

**Comment by zcahana** [comment]
Hi @aledbf, you're welcome to join the [Istio slack team](https://istio-dev.slack.com) where the developers hang out. Ingress-related functionality is mostly discussed at the #manager channel.

**Comment by aledbf** [comment]
@zcahana I tried but is required a @google.com, @us.ibm.com or @lyft.com email account

**Comment by zcahana** [comment]
That's probably needed for auto-admittance. I myself am @il.ibm.com, but doesn't recall how I got in ;).
Anyway, I sent an invite to the email address specified in your profile.

**Comment by aledbf** [comment]
@zcahana thanks!

**Comment by ijsnellf** [comment]
I believe this issue can be closed.
1. Where it makes sense, we are leveraging `GenericController`. `GenericController`'s IP address status syncer is being used to update the Ingress resource's IP address.
1. Our implementation is at rough parity with `GenericController`. We don't need to use anything else from `GenericController`. 
1. Architecturally, `GenericController` is coupled with K8S. Our implementation for generating Envoy configs based on Istio ingress rules is (more) agnostic than if we leveraged `GenericController` to do the same thing.

@zcahana @kyessenov: thoughts?

**Comment by kyessenov** [comment]
Sounds fare. From my look over generic controller, it's basically nginx controller generalized. Envoy is somewhat different. And I also agree with 3), ingress is not k8s-only concept, so we need an ingress proxies in other platforms, and generic controller doesn't cut it.

**Comment by zcahana** [comment]
Indeed sounds fair. Closing this.
