### ISSUE TITLE
Ingress controller: start proxy process regardless of existing ingress resources

### ISSUE THREAD

**Issue by zcahana** [istio/manager#220]
Currently the ingress controller's proxy is restarted every time a new configuration is created, which is triggered only when ingress or related API resources are created/modified. If there are no ingress resources at all, the proxy process is never started.

Instead, we can bootstrap and start the proxy with an initial configuration, so that requests that land on the ingress controller proxy provide some default response (e.g., 404).

**Comment by kyessenov** [comment]
Let me know if you think we need to extend the event queue in the controller to generate events from handlers.

**Comment by zcahana** [comment]
I was thinking that the `envoy.ingressWatcher` should `reload()` when initialized, and not wait for the first event to arrive. This may also apply to the "regular" `envoy.watcher`.
