### ISSUE TITLE
Envoy agent reuses old epochs

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#264]
Epoch 0 can come after epoch 9 - it seems it's better to always increment epochs for understanding failure logs.

**Comment by ayj** [comment]
Related to https://github.com/istio/manager/issues/77?

**Comment by kyessenov** [comment]
I think our watcher picks any int that's available (or so it looks like). I'll get to investigate this after I'm done with RDS.

**Comment by ijsnellf** [comment]
The current logic tries to select the highest running Envoy instance's restart epoch and increment that. If all the Envoy instances have exited, it will end up reverting to epoch 0.

**Comment by ijsnellf** [comment]
Last I checked, Envoy only supported incrementing the restart epoch by 1. So given Envoys running with restart epochs 7 and 8, and 8 dies unexpectedly, the only Envoy restart epoch that will allow the new Envoy instance to start is 8.

**Comment by kyessenov** [comment]
duplicate of #268
