### ISSUE TITLE
More flexibility deleting using istioctl

### ISSUE THREAD

**Issue by esnible** [istio/manager#298]
This issue is to incorporate the enhancement suggested by @frankbu on #286

I want to support `istioctl delete <type> <name> [<name2> ... <nameN> [-f <file.yaml>]`

The tool would delete all resources in the file, if it is specified.
The tool would delete all resources specified on the CLI directly, if any
If neither a name nor a file was specified, it would print an error.

**Comment by frankbu** [comment]
should that be: 
`istioctl delete (<type> <name> [<name2> ... <nameN>]) | (-f <file.yaml>)` ?
