### ISSUE TITLE
read kubeconfig via KUBECONFIG env variable

### ISSUE THREAD

**Issue by rshriram** [istio/manager#308]
if user has not provided explicit kubeconfig via the -c flag, istioctl should attempt to read the kubeconfig via KUBECONFIG env variable (which typically points to the kubernetes config).

Following the precedence mentioned in https://kubernetes.io/docs/user-guide/kubectl/kubectl_config/ might be useful (first preference to -c option, second to kubeconfig and final to $HOME/.kube/config)

**Comment by kyessenov** [comment]
The fallback to .kube/config already happens: https://github.com/istio/manager/blob/master/cmd/root.go#L53

**Comment by rshriram** [comment]
yes, but not to KUBECONFIG
