### ISSUE TITLE
istioctl: merge list into get route-rules|destination-policies

### ISSUE THREAD

**Issue by rshriram** [istio/manager#310]
Like kubectl, need to support plural of rules, such as 
`istioctl get route-rules`
`istioctl get destination-policies`

where the default listing is just the name of the route and ordered by precedence (and policy ordered alphabetically). With -o yaml, we could dump the same output as `istioctl list`. Once we have this, we can eliminate `istioctl list` and restrict istioctl to 4 verbs: `create|get|replace|delete`

**Comment by esnible** [comment]
@rshriram I assume `istioctl get route-rule` and `istioctl get route-rules` are synonyms, similar to `kubectl get pod`/`kubectl get pods`?
Are you sure that when the output is not YAML that only the name is desired?  I had hoped we would have a `--quiet` option that would output only the names, but that the default output would have a few columns, perhaps name, destination, and a flattened version of tags.
