### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by tacy** [istio/manager#368]
follow [the build instructions](https://github.com/istio/manager/blob/master/doc/build.md), I can't build success , error  msg: 

`WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 26 targets...
ERROR: missing input file '//platform/kube:config'.
ERROR: /home/tacy/workspace/go/mygo/src/istio.io/manager/model/BUILD:31:1: Executing genrule //model:genmocks failed: bash failed: error executing command
  (exec env - \
    PATH=/home/tacy/bin/google-cloud-sdk/bin:/home/tacy/workspace/go/go-tools/bin:/home/tacy/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/android-sdk/tools:/opt/android-sdk/platform-tools \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;  mockgen -source model/config.go -destination bazel-out/local-fastbuild/genfiles/model/mock_config_gen_test.go -package model')

Use --sandbox_debug to see verbose messages from the sandbox.
/bin/bash: mockgen: command not found
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
ERROR: /home/tacy/workspace/go/mygo/src/istio.io/manager/platform/kube/BUILD:38:1: //platform/kube:kubeconfig: missing input file '//platform/kube:config'.
ERROR: /home/tacy/workspace/go/mygo/src/istio.io/manager/platform/kube/BUILD:38:1 1 input file(s) do not exist.
INFO: Elapsed time: 0.306s, Critical Path: 0.13s`

**Comment by ayj** [comment]
> /bin/bash: mockgen: command not found

Did you run `bin/install-prereqs.sh` before running `bazel build //...`? That will install the build prerequisites including mockgen.

```
$ grep mockgen bin/install-prereqs.sh
# Install mockgen tool to generate golang mock interfaces
go get github.com/golang/mock/mockgen
```

**Comment by tacy** [comment]
I have runing `bin/install-prereqs.sh`, but $GOPATH/bin not in $PATH, sorry for the noise.  I usually install go-tools to other $GOPATH that  in $PATH.

close it, thanks @ayj

**Comment by kadamvandita** [comment]
Hi,

ERROR: missing input file '//platform/kube:config'. any fix for this?

**Comment by gyliu513** [comment]
@kadamvandita you may want to run `make platform/kube/config` or `make setup` first.
