### ISSUE TITLE
Istio config resources can be created for non-existent namespaces

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#372]
Apparently, k8s allows you to create TPRs for non-existent namespaces:
`istioctl create -f ... -n idontexist`
You can create namespace later and the resource is there. Resource is correctly cleaned up if you delete namespace though.

**Comment by kyessenov** [comment]
@sebastienvas discovered this

**Comment by rshriram** [comment]
Should we investigate using something like redis (like what mixer is doing) as our datastore backend? Or force mixer to go the other way. It seems we are heading for a data management nightmare with multiple data stores for the control plane (one platform dependent and one platform independent).

**Comment by kyessenov** [comment]
This is a bug specifically for kube binding. The design of the data store for Mixer is still under consideration. I agree that we should converge but I don't want to be blocked by lack of proper Mixer config. @mandarjog
