### ISSUE TITLE
new address form causes an assert failure in stats

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#386]
I think the new address form breaks some assertions in stats:
`[2017-03-24 03:18:34.082][21][critical][assert] assert failure: std::string::npos == name.find(':'): external/envoy_git/source/common/stats/stats_impl.cc:29`

To reproduce, run `bin/e2e.sh -debug`.

**Comment by kyessenov** [comment]
@qiwzhang @myidpt please run envoy tests with debug option, there seems to be a problem with the recent change.

**Comment by wattli** [comment]
This assert was added after my change. https://github.com/lyft/envoy/pull/597/files. Will look into it tomorrow

**Comment by myidpt** [comment]
I ran bin/e2e.sh -debug on the clean HEAD, and got the error in reachability.go:
I0323 22:09:46.737806   13549 reachability.go:86] Making a request http://a/t from t (attempt 3)...
I0323 22:09:46.737856   13549 driver.go:357] kubectl exec t-803097027-5gwcr -n istio-integration-bb8kr -c app -- client -url http://a/t

**Comment by wattli** [comment]
I always get an 'access denied' when run the command, @kyessenov , do i need to be in some group of istio/manager?

**Comment by ayj** [comment]
@wattli, do you have write access to gcr.io/istio-testing registry? You can use an alternate hub if necessary with the `-hub` option, e.g. `bin/e2e.sh -debug -hub docker.io/istio`

cc @sebastienvas

**Comment by myidpt** [comment]
Or you can ask Kuat to add you to the GCP project we use.

**Comment by wattli** [comment]
Chatted with Kuat offline, this is unrelated to my change. The root cause is here https://github.com/lyft/envoy/pull/597/files.

**Comment by qiwzhang** [comment]
Can we raise an issue for Envoy to ask them to fix it?  At the same time,
revert Envoy to a good SHA?

**Comment by wattli** [comment]
I got the same problem when run the integration test as Oliver:

I0324 13:56:25.016377   13857 driver.go:364] kubectl exec t-2658289576-hzikj -n istio-integration-pmqpm -c app -- client -url http://b.istio-integration-pmqpm:80/t
I0324 13:56:25.817920   13857 driver.go:170] failed to inject proxy from t to a (url http://a:8080/t)
I0324 13:56:25.817963   13857 driver.go:183] Cleaning up ingress secret.

**Comment by kyessenov** [comment]
#394
