### ISSUE TITLE
Validate rules and polices before istioctl sends them to kube client

### ISSUE THREAD

**Issue by esnible** [istio/manager#423]
The first implementation will be of the simple rules in issue #418

**Comment by rshriram** [comment]
why do we need another issue for the same issue ? Given that we are going to have a server side API, I would suggest that we just focus on #418, develop the validation library, use it temporarily and then when we have the server side, we can reuse it on server side.

**Comment by rshriram** [comment]
Closing this issue as duplicate of #418
