### ISSUE TITLE
Support HTTPS routing

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#47]
We need to investigate how to route HTTPS traffic for pod ingress/egress traffic. TCP-level sufficient but maybe SNI works better.

**Comment by rshriram** [comment]
Why can't we go one level further and use the http connection manager (envoy) itself ? All we need are the cert files. We can use the kube secrets to pass them around. WDYT ? Am I missing something?

**Comment by kyessenov** [comment]
If we want to terminate HTTPS then that's great, but I was referring to the case when the application container doesn't trust us with the certs.

**Comment by kyessenov** [comment]
We need to add server-side SNI to Envoy to support opaque HTTPS services on the same ports.
See https://github.com/lyft/envoy/issues/95.

**Comment by kyessenov** [comment]
We went with TCP based routing instead of SNI for opaque HTTPS.
#312

**Comment by kyessenov** [comment]
Implemented (modulo port-sharing issue #237)
