### ISSUE TITLE
Ingress controller: watch secrets referenced by ingresses

### ISSUE THREAD

**Issue by zcahana** [istio/manager#486]
Extend the `platform/kube.Controller` to watch secrets referenced within ingresses, and provide change notifications so that the proxy could be reloaded when a referenced secret changes.

Extend the `proxy/envoy.ingressWatcher` to subscribe for these notifications and reload certs/Envoy accordingly.

This can be used for in-place updates of TLS certificates stored in kube secrets.

**Comment by zcahana** [comment]
Priority for this issue is probably low at this point. I'm opening it mostly to capture this idea for later.

**Comment by ijsnellf** [comment]
Resolved by https://github.com/istio/manager/pull/563
