### ISSUE TITLE
Scale issues due to envoy polling manager for config every 1s

### ISSUE THREAD

**Issue by andraxylia** [istio/manager#497]
Istio does not scale with current design because all envoy instances poll istio-manager for config every 1s.

**Comment by ayj** [comment]
Please see https://github.com/istio/manager/issues/292 for additional discussion on scaling the discovery service. 

Short term plan is some combination of tweaking Envoy's RefreshDelayMs, increasing number of istio-manager replicas, and optimizing SDS/CDS/RDS response generation (see https://github.com/istio/manager/pull/455).

Long term plan is to investigate the use of gRPC streaming API for SDS/CDS/RDS. I'm tracking that issue [here](https://github.com/lyft/envoy/issues/368).

**Comment by andraxylia** [comment]
Will track this issue using #292, as long as I can edit 292's title.
