### ISSUE TITLE
Add TLS certificates configuration

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#52]
As part of the Mesh Config, we need to distribute certificates to Envoy proxies.
This can be done using Kubernetes Secrets and `envoy.MeshConfig` fields that are configurable as flags at start-up time. In the future, MeshConfig will be dynamically updated, but as the first step, we need to get certs loaded statically in Envoy.

**Comment by lookuptable** [comment]
What will the certificates be used for?

**Comment by kyessenov** [comment]
For SSL context in Envoy to terminate and initiate HTTPS connections (perhaps, for raw TCP as well?)

**Comment by ayj** [comment]
cc @lookuptable

**Comment by kyessenov** [comment]
Since there is a separate auth component, I'm reassigning it to @lookuptable. Please keep us in the loop on HTTPS termination solution.

**Comment by kyessenov** [comment]
This is done by Istio CA or by ingress proxy. Unifying the two is delayed to beta.
