### ISSUE TITLE
Add istioctl subcommands for mixer config API

### ISSUE THREAD

**Issue by ayj** [istio/manager#523]
The istioctl command line tool needs to support mixer config API CRUD operations. This can be implemented as a separate set of istioctl subcommands that CRUD mixer config resources through the mixer config API server.

This ultimately depends on completion https://github.com/istio/mixer/pull/525 for final integration test. However, the mixer API server and istioctl are in separate repos so we'll likely need to implement a fake mixer config API server in istio/manager for unit tests.

cc @esnible, @mandarjog

**Comment by kyessenov** [comment]
I wonder if it's worth publishing a schema for the mixer server surface as swagger/grpc so that we can derive a fake one easily.

**Comment by ayj** [comment]
Fixed by https://github.com/istio/manager/pull/560
