### ISSUE TITLE
istioctl kube-inject in a namespace

### ISSUE THREAD

**Issue by andraxylia** [istio/manager#569]
If user wants to deploy in a different namespace than default, they have to specify -n <ns> in the kube-inject command, in addition to specifying in kubectl command. Otherwise, the  error "Cannot find ConfigMap" is displayed, which does not offer a good indication of the problem.

Can we avoind having to specify -n, or at a minimum, display a more relevant error and a usage example?

**Comment by kyessenov** [comment]
if you don't specify `-n`, it will read mesh config from default namespace. If you try to deploy to non-default namespace, Istio will use mesh config from that namespace and will be very confusing which namespace config you are using.
