### ISSUE TITLE
Kubernetes Admission Controller for proxy injection

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#57]

**Comment by rshriram** [comment]
Bit more detail? Are we writing our own?

**Comment by kyessenov** [comment]
Yes, we need to inject sidecar proxy container to automate pod spec rewrite. There is no platform support, so the issue is track the upstream progress.

**Comment by ayj** [comment]
ref [Proposal: Extensible Admission Control](https://github.com/kubernetes/community/pull/132/)

**Comment by ayj** [comment]
Duplicate of https://github.com/istio/manager/issues/335
