### ISSUE TITLE
 istioctl kube-inject -f bookinfo.yaml fails with Error: ... No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by jwalters-gpsw** [istio/manager#593]
This is a 1.5.x Tectonic cluster using RBAC. I have several k8s contexts, but have tried both that have full cluster admin rights. 

`$ istioctl kube-inject -f bookinfo.yaml > bookinfo-out.yaml`
`Error: failed to connect to Kubernetes API. No Auth Provider found for name "oidc"`

Will look and see if I can figure out how the go client is being created.

**Comment by kyessenov** [comment]
The auth provider is difficult to use from k8s client-go client library. Therefore, we have been using self-contained client certificates as mentioned in the note 2 here: https://github.com/istio/manager/blob/master/doc/testing.md#getting-started

Let us know if you are aware of a better solution! We're actually moving away towards our own config server to avoid depending on k8s authentication, but that work is about 80% done.

**Comment by jwalters-gpsw** [comment]
I think you just need to include:

`_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"`

in the bottom of the imports in https://github.com/istio/manager/blob/master/cmd/istioctl/main.go

I just tried it with the example in https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster and it worked fine and respected the current context.

Tried it with your source code but I can't build. Must be a Bazel thing... getting

`$ go build .`
`mixer.go:28:2: no buildable Go source files in /Users/jwalters/go/src/github.com/googleapis/googleapis/google/rpc`
`../../../../../istio.io/manager/model/config.go:24:2: no buildable Go source files in /Users/jwalters/go/src/istio.io/api/proxy/v1/config`

**Comment by kyessenov** [comment]
Thanks. Your suggestion does indeed seems to work. There are some `doc/` files to help with building and debugging, but yes, you first need to build with bazel and then run `bin/init.sh` to use regular go tools.

**Comment by andraxylia** [comment]
We created new istio install files for RBAC enabled clusters, please have a look at istio/istio#150, and try to install https://github.com/istio/istio/blob/master/kubernetes/istio-16.yaml

**Comment by kyessenov** [comment]
#594
