### ISSUE TITLE
Building per instructions (tip of master) results in no such package '@org_golang_x_text//secure/precis' error 

### ISSUE THREAD

**Issue by jwalters-gpsw** [istio/manager#598]
Building per instructions (tip of master) results in no such package '@org_golang_x_text//secure/precis' error.

Using go1.8.1.
Bazel: Build label: 0.4.5-homebrew

`$ bazel build //...
ERROR: /private/var/tmp/_bazel_jwalters/09c8b9057a818f050ba6a327e7ad1a25/external/com_github_PuerkitoBio_purell/BUILD:5:1: no such package '@org_golang_x_text//secure/precis': failed to generate BUILD files for golang.org/x/text: 2017/04/26 08:59:55 open /private/var/tmp/_bazel_jwalters/09c8b9057a818f050ba6a327e7ad1a25/external/org_golang_x_text/collate/BUILD: is a directory
 and referenced by '@com_github_PuerkitoBio_purell//:go_default_library'.
ERROR: Analysis of target '//test/util:go_default_library' failed; build aborted.
INFO: Elapsed time: 158.415s`

**Comment by kyessenov** [comment]
Bazel has issues building go sources on darwin and cross-compiling to linux. I'd suggest using a linux VM if possible until we get those issues resolved upstream in bazel.

**Comment by kyessenov** [comment]
#20
