### ISSUE TITLE
istio.io/manager/client/proxy/ManagerClient should log HTTP

### ISSUE THREAD

**Issue by esnible** [istio/manager#645]
istio.io/manager/client/proxy/ManagerClient should log HTTP, similar to what the Kubernetes clients do.

Running _istioctl_ with `-v 999` or similar HTTP done by kubernetes/client-go is logged like this:

```
I0503 08:57:03.503956   98299 round_trippers.go:398] curl -k -v -XGET  -H "Accept: application/json, */*" https://192.168.99.101:8443/apis/istio.io/v1alpha1/istioconfigs
I0503 08:57:03.505300   98299 round_trippers.go:417] GET https://192.168.99.101:8443/apis/istio.io/v1alpha1/istioconfigs 200 OK in 1 milliseconds
```

**Comment by esnible** [comment]
@kyessenov I wish to get your advice on the approach to this.

The easiest thing is to add a few lines of glog logging to client/proxy/proxy.go method Do()

Better would be to wrap the http.Client used by Do() with https://github.com/kubernetes/client-go/blob/master/transport/round_trippers.go so that we would get exactly the same logging.  I am not sure if this would be trivial or difficult.  It would also introduce a Kubernetes dependency in an Istio package outside "platform".

**Comment by kyessenov** [comment]
I don't think we need much complexity to log HTTP requests. Our config API is very small unlike kubernetes API. Maybe just sprinkle glogs for "GET authority/uri 200" messages?
