### ISSUE TITLE
proxy segfault

### ISSUE THREAD

**Issue by costinm** [istio/manager#656]
Happened after testing with ~1000 requests for a long time.

Stack trace on envoy:

(gdb) bt
#0  0x0000000003357c08 in ?? ()
#1  0x0000000000448acf in std::_Function_handler<void (google::protobuf::util::Status const&), Http::Mixer::Instance::decodeHeaders(Http::HeaderMap&, bool)::{lambda(google::protobuf::util::Status const&)#1}>::_M_invoke(std::_Any_data const&, google::protobuf::util::Status const&) ()
#2  0x0000000000526946 in Event::DispatcherImpl::runPostCallbacks() ()
#3  0x000000000078ef81 in event_process_active_single_queue (base=base@entry=0x308e2c0, activeq=0x2efc210, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1646
#4  0x000000000078f887 in event_process_active (base=0x308e2c0) at event.c:1738
#5  event_base_loop (base=0x308e2c0, flags=0) at event.c:1961
#6  0x00000000005213d1 in Worker::threadRoutine(Server::GuardDog&) ()
#7  0x00000000005c797e in Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) ()
#8  0x00007f3a7aec766a in __reclaim_stacks () at allocatestack.c:946
#9  0xa7db176b218c89d7 in ?? ()
#10 0x0000000000000000 in ?? ()

**Comment by kyessenov** [comment]
@qiwzhang @mandarjog another race...

**Comment by qiwzhang** [comment]
Created https://github.com/istio/proxy/issues/286 in istio/proxy

**Comment by qiwzhang** [comment]
Could you

**Comment by qiwzhang** [comment]
@costinm which version of proxy are you using?   It seems I may have fixed it by https://github.com/istio/proxy/pull/280

**Comment by kyessenov** [comment]
please follow the issue upstream in istio/proxy.
