### ISSUE TITLE
Add pre-submit checks and CI

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#7]
The tests in Manager require an access to a GKE cluster to run the integration test.
That means Jenkins/GKE is probably a better choice for CI than Travis.

**Comment by sebastienvas** [comment]
But you still have some unittest that could easily run on Travis right ?

**Comment by kyessenov** [comment]
Correct. But I'm also using Bazel for running Kubernetes tests. I'd like to have those in CI. So if you have a choice to get with Jenkins or Travis, can we go with Jenkins?

**Comment by sebastienvas** [comment]
The plan is to go with both for now. Travis to prepare the PR for review and Jenkins to do the heavy lifting. We might drop Travis in the future.

**Comment by kyessenov** [comment]
We dropped Travis since we very much depend on kubernetes to exercise code in Manager.
Closed by #64
