### ISSUE TITLE
support for headless services

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#718]
Need to filter services that have no IP to prevent envoy from crash looping.

**Comment by ijsnellf** [comment]
Basically just filter out services where `addr == ""`?
```golang
func convertService(svc v1.Service) *model.Service {
	addr, external := "", ""
	if svc.Spec.ClusterIP != "" && svc.Spec.ClusterIP != v1.ClusterIPNone {
		addr = svc.Spec.ClusterIP
	}
```

**Comment by kyessenov** [comment]
Yes, we should ignore all routing for headless services. Basically, skip over all services with empty `addr`.
