### ISSUE TITLE
Fault Injection not working for Ingress

### ISSUE THREAD

**Issue by smawson** [istio/manager#723]
I defined a fault injection rule:

type: route-rule
name: frontend-rule
spec:
  destination: frontend.default.svc.cluster.local
  httpFault:
    delay:
      percent: 100
      fixedDelay: 5s

This doesn't seem to work when going through ingress, although other rules (such as timeouts) work fine.

**Comment by kyessenov** [comment]
Thanks! This is a true issue (fault filter is not playing nicely with RDS)

**Comment by kyessenov** [comment]
closing, filed #731 and https://github.com/istio/istio.github.io/issues/202
