### ISSUE TITLE
`istioctl mixer create rule` for invalid rule incorrectly claims reason not provided

### ISSUE THREAD

**Issue by esnible** [istio/manager#740]
When I do ```$ istioctl mixer rule create global myservice.ns.svc.cluster.local --file tests/apps/istioctl/input/mixer-rule-ratings-ratelimit-invalid.yaml Error: the server responded with the status code 412 but did not return more information```

The "did not return more information" message is not correct.  When istioctl is run with -v 9999 the logs show that the mixer is returning output.  (There is code there that is supposed to decode this, but that code is never invoked because `mixerRESTRequester.Request()` returns an error.

Response Body: {
  "status": {
   "code": 9,
   "message": "2 errors occurred:\n\n* serviceConfig: failed validation\n* /:quotas[0]: failed to parse params: 1 error occurred:\n\n* quotas: aspect validation failed: 1 error occurred:\n\n* maxAmount: must be \u003e= 0"
  }
 }

The error code should be 400 not 412.  I opened a separate bug in istio/mixer for that.

The rule I tested with is not merged, but can be seen at https://github.com/istio/istio/pull/265/files#diff-1afd3a79d99bc64d1a07c3441d49fc51

**Comment by kyessenov** [comment]
Ed, these must be coming from here https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go#L15. The underlying reason is maybe that Mixer is not setting GRPC error code correctly.

**Comment by mandarjog** [comment]
@esnible  since you have updated the api server recently you are welcome to take this.
We are just generating an incorrect status code here. 

https://github.com/istio/mixer/blob/master/pkg/config/apiserver.go#L253
