### ISSUE TITLE
`istioctl delete` should not give up when deleting multiple rules on the first failure

### ISSUE THREAD

**Issue by esnible** [istio/manager#771]
@frankbu says "Like _kubectl_, I think it should delete whatever it can, and print out messages about the ones that are not found"

To reproduce:

```
istioctl create -f route-rule-all-v1.yaml
istioctl delete route-rule foo productpage-default bar reviews-default
istioctl get route-rules
```

**Comment by frankbu** [comment]
Another thought, in addition to this, it might be nice to add a `--all` option like kubectl
```
istioctl  delete route-rule --all
```

**Comment by esnible** [comment]
When I want to delete all of the rules I do ```istioctl get route-rules | xargs istioctl delete route-rule`.  Similar to what I do deleting images in _docker_.  If you desire `--all` file it in a new Issue.
