### ISSUE TITLE
New envoy config for mixer server for Unary mixer api

### ISSUE THREAD

**Issue by qiwzhang** [istio/manager#820]
Unary implementation, mixer server should be specified in "cluster_manager". 

Changes are
1) remove mixer_server from filter config
2) add following to "cluster_manager"

"cluster_manager": {
    "clusters": [
     ...,
     {
        "name": "mixer_server",
        "connect_timeout_ms": 5000,
        "type": "strict_dns",
        "circuit_breakers": {
           "default": {
              "max_pending_requests": 10000,
              "max_requests": 10000
            }
        },
        "lb_type": "round_robin",
        "features": "http2",
        "hosts": [
          {
            "url": "tcp://${MIXER_SERVER}"
          }
        ]
     }

All unary code are in "unary" branch now.  This code should be in "unary" branch too.  Once everything is ready, we will merge them back to master all in one shot.

**Comment by qiwzhang** [comment]
@kyessenov could you help?

**Comment by kyessenov** [comment]
#822
